// scripts/__tests__/knob-anchors.test.ts
// Every knob /hitl:customize offers has an anchor, and every anchor names a knob.
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { GENERATED_KNOBS, KNOBS } from "../../installer/lib.mjs";

const ROOT = process.cwd();
const ANCHOR = /^<!-- hitl:knob ([a-z-]+) -->$/;

function templateFiles(): string[] {
  return readdirSync(join(ROOT, "templates"), { recursive: true, encoding: "utf8" })
    .filter((p) => p.endsWith(".md"))
    .map((p) => join("templates", p));
}

function anchorsIn(text: string): { id: string; next: string }[] {
  const lines = text.split("\n");
  const out: { id: string; next: string }[] = [];
  lines.forEach((line, i) => {
    const m = line.match(ANCHOR);
    if (m) out.push({ id: m[1], next: lines[i + 1] ?? "" });
  });
  return out;
}

describe("knob anchors", () => {
  const found = templateFiles().flatMap((p) =>
    anchorsIn(readFileSync(join(ROOT, p), "utf8")).map((a) => ({ ...a, file: p })),
  );

  it("has ten knobs, three of them generated by code", () => {
    expect(KNOBS).toHaveLength(10);
    expect(GENERATED_KNOBS.every((k) => KNOBS.includes(k))).toBe(true);
  });

  for (const id of KNOBS.filter((k) => !GENERATED_KNOBS.includes(k))) {
    it(`knob ${id} is anchored in at least one template`, () => {
      expect(found.filter((a) => a.id === id).length).toBeGreaterThan(0);
    });
  }

  it("review-rounds is anchored at every restatement", () => {
    const files = found.filter((a) => a.id === "review-rounds").map((a) => a.file);
    expect(files.filter((f) => f === "templates/HITL.md")).toHaveLength(4);
    expect(files.filter((f) => f.endsWith("review-spec.md"))).toHaveLength(2);
    expect(files.filter((f) => f.endsWith("review-plan.md"))).toHaveLength(2);
  });

  it("severities and reporting-cap are anchored in all three reviewers", () => {
    for (const id of ["severities", "reporting-cap"]) {
      const files = found.filter((a) => a.id === id).map((a) => a.file);
      for (const r of ["spec-reviewer", "plan-reviewer", "slice-reviewer"]) {
        expect(
          files.some((f) => f.endsWith(`${r}.md`)),
          `${id} in ${r}`,
        ).toBe(true);
      }
    }
  });

  it("every anchor in the templates names a listed knob", () => {
    for (const a of found) expect(KNOBS, `${a.file}: ${a.id}`).toContain(a.id);
  });

  it("every anchor is immediately followed by a non-empty line", () => {
    for (const a of found) expect(a.next.trim(), `${a.file}: ${a.id}`).not.toBe("");
  });

  it("this repository's HITL.md carries the invariants section", () => {
    const text = readFileSync(join(ROOT, "HITL.md"), "utf8");
    expect(text).toContain("## Load-bearing invariants");
    expect(text).toContain(
      "MISSING · UNCLEAR · CONFLICTS · BREAKS · UNPROVEN · MIS-SLICED · DEFERRED",
    );
  });
});
